// Generated by scripts/validate-locales.mjs --generate. Do not edit.
export interface MessageCatalog {
  "common": {
    "actions.apply": Record<string, never>
    "actions.cancel": Record<string, never>
    "actions.clear": Record<string, never>
    "actions.close": Record<string, never>
    "actions.done": Record<string, never>
    "actions.openMenu": Record<string, never>
    "actions.refresh": Record<string, never>
    "actions.reset": Record<string, never>
    "actions.retry": Record<string, never>
    "actions.save": Record<string, never>
    "copy.failed": Record<string, never>
    "copy.link": Record<string, never>
    "copy.success": Record<string, never>
    "filters.clearSelection": { "label": string | number }
    "filters.close": Record<string, never>
    "filters.description": Record<string, never>
    "filters.title": Record<string, never>
    "greeting": { "name": string | number }
    "items": { "count": number }
    "locale.changeFailed": Record<string, never>
    "locale.label": Record<string, never>
    "locale.selected": { "language": string | number }
    "locale.switching": Record<string, never>
    "pagination.next": Record<string, never>
    "pagination.noPages": Record<string, never>
    "pagination.page": { "page": string | number }
    "pagination.pageSize": Record<string, never>
    "pagination.pageSummary": { "count": number; "page": string | number }
    "pagination.perPage": { "size": string | number }
    "pagination.previous": Record<string, never>
    "pagination.total": { "value": string | number }
    "phone.countryCode": Record<string, never>
    "refresh.updated": { "time": string | number }
    "search.apply": Record<string, never>
    "search.clear": Record<string, never>
    "states.empty": Record<string, never>
    "states.emptyDescription": Record<string, never>
    "states.error": Record<string, never>
    "states.errorDescription": Record<string, never>
    "states.loading": Record<string, never>
    "states.loadingDescription": Record<string, never>
    "states.loadingOption": Record<string, never>
    "states.noAccess": Record<string, never>
    "states.noAccessDescription": Record<string, never>
    "states.unavailable": Record<string, never>
    "table.close": Record<string, never>
    "table.columns": Record<string, never>
    "table.description": Record<string, never>
    "table.hidden": { "label": string | number }
    "table.move": { "label": string | number }
    "table.moved": { "label": string | number; "position": string | number }
    "table.moveDown": { "label": string | number }
    "table.moveUp": { "label": string | number }
    "table.reset": Record<string, never>
    "table.restored": Record<string, never>
    "table.settings": Record<string, never>
    "table.shown": { "label": string | number }
    "table.title": { "table": string | number }
    "table.trigger": Record<string, never>
    "table.visibility": { "label": string | number }
    "theme.current": { "label": string | number }
    "theme.dark": Record<string, never>
    "theme.label": Record<string, never>
    "theme.light": Record<string, never>
    "theme.next": { "label": string | number }
    "theme.system": Record<string, never>
    "toast.close": Record<string, never>
    "toast.notification": Record<string, never>
    "toast.viewport": { "hotkey": string | number }
  }
  "shell": {
    "header.demo": Record<string, never>
    "header.profile": Record<string, never>
    "header.profileMenu": Record<string, never>
    "header.user": Record<string, never>
    "navigation.account": Record<string, never>
    "navigation.bankAccounts": Record<string, never>
    "navigation.cashiers": Record<string, never>
    "navigation.close": Record<string, never>
    "navigation.collapse": Record<string, never>
    "navigation.dashboard": Record<string, never>
    "navigation.description": Record<string, never>
    "navigation.desktop": Record<string, never>
    "navigation.devices": Record<string, never>
    "navigation.dynamicQr": Record<string, never>
    "navigation.dynamicQrPreview": Record<string, never>
    "navigation.empty": Record<string, never>
    "navigation.expand": Record<string, never>
    "navigation.home": Record<string, never>
    "navigation.main": Record<string, never>
    "navigation.mobile": Record<string, never>
    "navigation.open": Record<string, never>
    "navigation.sections": Record<string, never>
    "navigation.staticQr": Record<string, never>
    "navigation.staticQrPreview": Record<string, never>
    "navigation.terminals": Record<string, never>
    "recovery.description": Record<string, never>
    "recovery.reload": Record<string, never>
    "recovery.title": Record<string, never>
    "routes.accountLoading": Record<string, never>
    "routes.bankAccountsLoading": Record<string, never>
    "routes.cashiersLoading": Record<string, never>
    "routes.createQrLoading": Record<string, never>
    "routes.dashboardLoading": Record<string, never>
    "routes.devicesLoading": Record<string, never>
    "routes.dynamicQrLoading": Record<string, never>
    "routes.exportLoading": Record<string, never>
    "routes.forbidden": Record<string, never>
    "routes.forbiddenDescription": Record<string, never>
    "routes.integrationUnavailable": Record<string, never>
    "routes.notFound": Record<string, never>
    "routes.notFoundDescription": Record<string, never>
    "routes.returnSafe": Record<string, never>
    "routes.sessionDescription": Record<string, never>
    "routes.sessionLoading": Record<string, never>
    "routes.staticQrLoading": Record<string, never>
    "routes.terminalsLoading": Record<string, never>
    "routes.unavailable": Record<string, never>
    "unavailable.bankAccountsDescription": Record<string, never>
    "unavailable.bankAccountsTitle": Record<string, never>
    "unavailable.cashiersDescription": Record<string, never>
    "unavailable.cashiersTitle": Record<string, never>
    "unavailable.dashboardDescription": Record<string, never>
    "unavailable.dashboardTitle": Record<string, never>
    "unavailable.devicesDescription": Record<string, never>
    "unavailable.devicesTitle": Record<string, never>
    "unavailable.dynamicQrDescription": Record<string, never>
    "unavailable.dynamicQrTitle": Record<string, never>
    "unavailable.exportQrDescription": Record<string, never>
    "unavailable.exportQrTitle": Record<string, never>
    "unavailable.staticQrDescription": Record<string, never>
    "unavailable.staticQrTitle": Record<string, never>
    "unavailable.terminalsDescription": Record<string, never>
    "unavailable.terminalsTitle": Record<string, never>
    "workspace": Record<string, never>
  }
  "auth": {
    "actions.continue": Record<string, never>
    "actions.forgotPin": Record<string, never>
    "actions.logout": Record<string, never>
    "actions.resend": Record<string, never>
    "actions.restart": Record<string, never>
    "actions.savePin": Record<string, never>
    "actions.signIn": Record<string, never>
    "actions.verify": Record<string, never>
    "brand.subtitle": Record<string, never>
    "completion.checking": Record<string, never>
    "completion.checkingDescription": Record<string, never>
    "completion.complete": Record<string, never>
    "completion.completeDescription": Record<string, never>
    "failure.description": Record<string, never>
    "failure.title": Record<string, never>
    "feedback.blocked": Record<string, never>
    "feedback.browserUnsupported": Record<string, never>
    "feedback.complete": Record<string, never>
    "feedback.completing": Record<string, never>
    "feedback.contract": Record<string, never>
    "feedback.deviceStorageUnavailable": Record<string, never>
    "feedback.invalidOtp": Record<string, never>
    "feedback.invalidPhone": Record<string, never>
    "feedback.invalidPin": Record<string, never>
    "feedback.otpExpired": Record<string, never>
    "feedback.otpNotExpired": Record<string, never>
    "feedback.ownerBusy": Record<string, never>
    "feedback.pinMismatch": Record<string, never>
    "feedback.rateLimited": Record<string, never>
    "feedback.request": Record<string, never>
    "feedback.sessionExpired": Record<string, never>
    "feedback.unavailable": Record<string, never>
    "feedback.wrongOtp": Record<string, never>
    "feedback.wrongPin": Record<string, never>
    "login.confirmDetails": Record<string, never>
    "login.description": Record<string, never>
    "login.phone": Record<string, never>
    "login.phoneSummary": { "phone": string | number }
    "login.title": Record<string, never>
    "logout.remoteUnconfirmed": Record<string, never>
    "otp.title": Record<string, never>
    "otp.validity": Record<string, never>
    "pin.confirm": Record<string, never>
    "pin.createTitle": Record<string, never>
    "pin.hide": Record<string, never>
    "pin.hideConfirmation": Record<string, never>
    "pin.new": Record<string, never>
    "pin.repeat": Record<string, never>
    "pin.show": Record<string, never>
    "pin.showConfirmation": Record<string, never>
    "pin.title": Record<string, never>
    "states.checking": Record<string, never>
    "states.saving": Record<string, never>
    "states.signingOut": Record<string, never>
    "states.waiting": Record<string, never>
  }
  "account": {
    "actions.refresh": Record<string, never>
    "feedback.changed": Record<string, never>
    "feedback.failed": Record<string, never>
    "feedback.unchanged": Record<string, never>
    "profile.fullName": Record<string, never>
    "profile.missing": Record<string, never>
    "profile.phone": Record<string, never>
    "states.refreshing": Record<string, never>
    "title": Record<string, never>
  }
  "dashboard": {
    "dates.choose": Record<string, never>
    "dates.graphPeriod": { "from": string | number; "to": string | number }
    "dates.hourAcross": { "end": string | number; "endDate": string | number; "start": string | number; "startDate": string | number }
    "dates.hourSame": { "date": string | number; "end": string | number; "start": string | number }
    "dates.interval": { "end": string | number; "start": string | number }
    "dates.next": Record<string, never>
    "dates.previous": Record<string, never>
    "dates.reset": Record<string, never>
    "dates.week": { "date": string | number }
    "donut.amountMismatch": Record<string, never>
    "donut.countMismatch": Record<string, never>
    "donut.details": Record<string, never>
    "donut.empty": Record<string, never>
    "donut.relative": Record<string, never>
    "donut.shareItem": { "label": string | number; "percent": string | number }
    "donut.successShare": Record<string, never>
    "donut.title": Record<string, never>
    "donut.total": { "countText": string | number }
    "donut.unavailable": Record<string, never>
    "filters.allTerminals": Record<string, never>
    "filters.dates": Record<string, never>
    "filters.invalid": Record<string, never>
    "filters.noTerminal": Record<string, never>
    "filters.preset": { "count": number }
    "filters.presets": Record<string, never>
    "filters.terminal": Record<string, never>
    "filters.terminalError": Record<string, never>
    "filters.terminalUnavailable": Record<string, never>
    "granularity.AUTO": Record<string, never>
    "granularity.DAY": Record<string, never>
    "granularity.groupDAY": Record<string, never>
    "granularity.groupHOUR": Record<string, never>
    "granularity.groupMONTH": Record<string, never>
    "granularity.groupWEEK": Record<string, never>
    "granularity.groupYEAR": Record<string, never>
    "granularity.HOUR": Record<string, never>
    "granularity.label": Record<string, never>
    "granularity.MONTH": Record<string, never>
    "granularity.WEEK": Record<string, never>
    "granularity.YEAR": Record<string, never>
    "growth.downFavorable": Record<string, never>
    "growth.downNeutral": Record<string, never>
    "growth.downUnfavorable": Record<string, never>
    "growth.unavailable": Record<string, never>
    "growth.unchanged": Record<string, never>
    "growth.upFavorable": Record<string, never>
    "growth.upNeutral": Record<string, never>
    "growth.upUnfavorable": Record<string, never>
    "metrics.failed": Record<string, never>
    "metrics.failedDescription": Record<string, never>
    "metrics.processing": Record<string, never>
    "metrics.processingDescription": Record<string, never>
    "metrics.share": { "label": string | number }
    "metrics.success": Record<string, never>
    "metrics.successDescription": Record<string, never>
    "metrics.summary": Record<string, never>
    "metrics.total": Record<string, never>
    "metrics.totalDescription": Record<string, never>
    "metrics.uncategorized": Record<string, never>
    "qrStatus.cancelled": Record<string, never>
    "qrStatus.expired": Record<string, never>
    "qrStatus.new": Record<string, never>
    "qrStatus.processing": Record<string, never>
    "qrStatus.rejected": Record<string, never>
    "qrStatus.success": Record<string, never>
    "qrStatus.unknown": Record<string, never>
    "recentQr.actions": Record<string, never>
    "recentQr.amount": Record<string, never>
    "recentQr.createdAt": Record<string, never>
    "recentQr.description": Record<string, never>
    "recentQr.empty": Record<string, never>
    "recentQr.error": Record<string, never>
    "recentQr.loading": Record<string, never>
    "recentQr.qrId": Record<string, never>
    "recentQr.refreshing": Record<string, never>
    "recentQr.stale": Record<string, never>
    "recentQr.status": Record<string, never>
    "recentQr.terminal": Record<string, never>
    "recentQr.title": Record<string, never>
    "recentQr.viewAll": Record<string, never>
    "recentQr.viewDetails": Record<string, never>
    "recentQr.viewQr": Record<string, never>
    "states.integrationDescription": Record<string, never>
    "states.integrationTitle": Record<string, never>
    "states.loading": Record<string, never>
    "states.noAccess": Record<string, never>
    "states.stale": Record<string, never>
    "states.updatedAt": { "time": string | number }
    "trend.amount": Record<string, never>
    "trend.amountUnit": Record<string, never>
    "trend.count": Record<string, never>
    "trend.countUnit": Record<string, never>
    "trend.coverageTitle": { "coverage": string | number; "title": string | number }
    "trend.empty": Record<string, never>
    "trend.exactDescription": Record<string, never>
    "trend.exactItem": { "amount": string | number; "countText": string | number; "label": string | number }
    "trend.exactTitle": Record<string, never>
    "trend.failed": Record<string, never>
    "trend.future": Record<string, never>
    "trend.grouping": { "group": string | number }
    "trend.keyboard": Record<string, never>
    "trend.mode": Record<string, never>
    "trend.partial": Record<string, never>
    "trend.series": Record<string, never>
    "trend.settings": Record<string, never>
    "trend.settingsHelp": Record<string, never>
    "trend.settingsTitle": Record<string, never>
    "trend.title": Record<string, never>
  }
  "dynamicQr": {
    "actions.details": Record<string, never>
    "actions.new": Record<string, never>
    "actions.viewQr": Record<string, never>
    "cancel.checkFirst": Record<string, never>
    "cancel.confirm": Record<string, never>
    "cancel.confirmed": Record<string, never>
    "cancel.id": { "id": string | number }
    "cancel.noRetry": Record<string, never>
    "cancel.notSent": Record<string, never>
    "cancel.notSentDetail": { "reason": string | number }
    "cancel.refreshFailed": Record<string, never>
    "cancel.rejected": Record<string, never>
    "cancel.title": Record<string, never>
    "cancel.unknown": Record<string, never>
    "cancel.warning": Record<string, never>
    "create.amount": Record<string, never>
    "create.bounds": { "maximum": string | number; "minimum": string | number }
    "create.boundsUnavailable": Record<string, never>
    "create.checkFirst": Record<string, never>
    "create.chooseTerminal": Record<string, never>
    "create.closed": Record<string, never>
    "create.currenciesFailed": Record<string, never>
    "create.currenciesLoading": Record<string, never>
    "create.currenciesUnavailable": Record<string, never>
    "create.currencyNoAccess": Record<string, never>
    "create.description": Record<string, never>
    "create.dialogHelp": Record<string, never>
    "create.example": Record<string, never>
    "create.failed": Record<string, never>
    "create.linkUnavailable": Record<string, never>
    "create.newRisk": Record<string, never>
    "create.noUzs": Record<string, never>
    "create.pending": Record<string, never>
    "create.resultHelp": Record<string, never>
    "create.submit": Record<string, never>
    "create.terminalNoAccess": Record<string, never>
    "create.terminalRemoved": Record<string, never>
    "create.terminalsEmpty": Record<string, never>
    "create.terminalsFailed": Record<string, never>
    "create.terminalsLoading": Record<string, never>
    "create.terminalsUnavailable": Record<string, never>
    "create.title": Record<string, never>
    "create.unknown": Record<string, never>
    "dates.choose": Record<string, never>
    "dates.next": Record<string, never>
    "dates.previous": Record<string, never>
    "dates.reset": Record<string, never>
    "details.bankId": Record<string, never>
    "details.baseAmount": Record<string, never>
    "details.currency": Record<string, never>
    "details.currencyAmount": Record<string, never>
    "details.distributionCode": Record<string, never>
    "details.linkSection": Record<string, never>
    "details.main": Record<string, never>
    "details.merchantId": Record<string, never>
    "details.noLink": Record<string, never>
    "details.payment": Record<string, never>
    "details.rate": Record<string, never>
    "details.statusCode": Record<string, never>
    "details.technical": Record<string, never>
    "details.terminalId": Record<string, never>
    "details.terminalName": Record<string, never>
    "details.terminalType": Record<string, never>
    "details.title": Record<string, never>
    "display.canonical": Record<string, never>
    "display.description": Record<string, never>
    "display.link": Record<string, never>
    "display.metadata": Record<string, never>
    "display.noLink": Record<string, never>
    "display.poster": Record<string, never>
    "display.posterAlt": Record<string, never>
    "display.qrTitle": Record<string, never>
    "display.title": Record<string, never>
    "distribution.created": Record<string, never>
    "distribution.expired": Record<string, never>
    "distribution.rejected": Record<string, never>
    "download.failed": Record<string, never>
    "download.pdf": Record<string, never>
    "download.png": Record<string, never>
    "download.posterFailed": Record<string, never>
    "download.posterLoading": Record<string, never>
    "export.failed": Record<string, never>
    "export.label": Record<string, never>
    "export.pending": Record<string, never>
    "export.stop": Record<string, never>
    "export.success": Record<string, never>
    "export.title": Record<string, never>
    "export.unavailable": Record<string, never>
    "feedback.alreadySent": Record<string, never>
    "feedback.copyId": Record<string, never>
    "feedback.createNotSent": Record<string, never>
    "feedback.createRejected": Record<string, never>
    "feedback.idCopied": Record<string, never>
    "feedback.idFailed": Record<string, never>
    "feedback.linkCopied": Record<string, never>
    "feedback.linkFailed": Record<string, never>
    "feedback.permission": Record<string, never>
    "feedback.selection": Record<string, never>
    "feedback.unavailable": Record<string, never>
    "filters.all": Record<string, never>
    "filters.allBanks": Record<string, never>
    "filters.allMerchants": Record<string, never>
    "filters.allTerminals": Record<string, never>
    "filters.applySearch": Record<string, never>
    "filters.banksFailed": Record<string, never>
    "filters.checking": Record<string, never>
    "filters.checkOrClear": Record<string, never>
    "filters.clear": Record<string, never>
    "filters.clearSearch": Record<string, never>
    "filters.clearSelection": Record<string, never>
    "filters.distribution": Record<string, never>
    "filters.invalid": Record<string, never>
    "filters.merchantsFailed": Record<string, never>
    "filters.noBanks": Record<string, never>
    "filters.noExpansion": Record<string, never>
    "filters.noMerchantBanks": Record<string, never>
    "filters.noMerchants": Record<string, never>
    "filters.search": Record<string, never>
    "filters.searchShort": Record<string, never>
    "filters.unavailable": Record<string, never>
    "page.empty": Record<string, never>
    "page.emptyHigh": Record<string, never>
    "page.first": Record<string, never>
    "page.firstHelp": Record<string, never>
    "page.integration": Record<string, never>
    "page.list": Record<string, never>
    "page.loading": Record<string, never>
    "page.name": Record<string, never>
    "page.noAccess": Record<string, never>
    "page.pages": Record<string, never>
    "page.stale": Record<string, never>
    "page.total": { "countText": string | number }
    "stats.failed": Record<string, never>
    "stats.fee": Record<string, never>
    "stats.total": Record<string, never>
    "stats.unavailable": Record<string, never>
    "status.cancelled": Record<string, never>
    "status.expired": Record<string, never>
    "status.new": Record<string, never>
    "status.processing": Record<string, never>
    "status.rejected": Record<string, never>
    "status.success": Record<string, never>
    "status.unknown": Record<string, never>
    "table.actions": Record<string, never>
    "table.amount": Record<string, never>
    "table.bank": Record<string, never>
    "table.createdAt": Record<string, never>
    "table.merchant": Record<string, never>
    "table.qrId": Record<string, never>
    "table.rrn": Record<string, never>
    "table.state": Record<string, never>
    "table.status": Record<string, never>
    "table.terminal": Record<string, never>
    "table.updatedAt": Record<string, never>
    "validation.amount": Record<string, never>
  }
  "staticQr": {
    "actions.details": Record<string, never>
    "actions.viewQr": Record<string, never>
    "details.bounds": Record<string, never>
    "details.links": Record<string, never>
    "details.main": Record<string, never>
    "details.region": Record<string, never>
    "details.technical": Record<string, never>
    "details.title": Record<string, never>
    "display.noLink": Record<string, never>
    "fields.createdAt": Record<string, never>
    "fields.district": Record<string, never>
    "fields.districtId": Record<string, never>
    "fields.link": Record<string, never>
    "fields.maximum": Record<string, never>
    "fields.merchant": Record<string, never>
    "fields.merchantId": Record<string, never>
    "fields.minimum": Record<string, never>
    "fields.qrId": Record<string, never>
    "fields.redirect": Record<string, never>
    "fields.region": Record<string, never>
    "fields.regionId": Record<string, never>
    "fields.status": Record<string, never>
    "fields.statusCode": Record<string, never>
    "fields.terminal": Record<string, never>
    "fields.terminalId": Record<string, never>
    "fields.terminalName": Record<string, never>
    "fields.terminalType": Record<string, never>
    "fields.updatedAt": Record<string, never>
    "filters.allDistricts": Record<string, never>
    "filters.allMerchants": Record<string, never>
    "filters.allRegions": Record<string, never>
    "filters.allTerminals": Record<string, never>
    "filters.chooseRegion": Record<string, never>
    "filters.districtsFailed": Record<string, never>
    "filters.invalid": Record<string, never>
    "filters.merchantsFailed": Record<string, never>
    "filters.noDistricts": Record<string, never>
    "filters.noMerchants": Record<string, never>
    "filters.noMerchantTerminals": Record<string, never>
    "filters.noRegions": Record<string, never>
    "filters.noTerminals": Record<string, never>
    "filters.regionsFailed": Record<string, never>
    "filters.reselect": Record<string, never>
    "filters.terminalsFailed": Record<string, never>
    "filters.unconfirmed": Record<string, never>
    "page.authUnavailable": Record<string, never>
    "page.name": Record<string, never>
    "page.noAccess": Record<string, never>
    "page.unavailable": Record<string, never>
    "search.label": Record<string, never>
    "search.placeholder": Record<string, never>
    "states.empty": Record<string, never>
    "states.failed": Record<string, never>
    "states.loading": Record<string, never>
    "status.active": Record<string, never>
    "status.unknown": Record<string, never>
    "table.actions": Record<string, never>
    "table.label": Record<string, never>
    "table.pages": Record<string, never>
    "table.total": { "countText": string | number }
  }
  "terminals": {
    "actions.details": Record<string, never>
    "actions.viewQr": Record<string, never>
    "details.contact": Record<string, never>
    "details.location": Record<string, never>
    "details.main": Record<string, never>
    "details.qr": Record<string, never>
    "details.title": Record<string, never>
    "display.noLink": Record<string, never>
    "display.unavailable": Record<string, never>
    "fields.address": Record<string, never>
    "fields.bank": Record<string, never>
    "fields.bankId": Record<string, never>
    "fields.createdAt": Record<string, never>
    "fields.district": Record<string, never>
    "fields.districtId": Record<string, never>
    "fields.mcc": Record<string, never>
    "fields.merchant": Record<string, never>
    "fields.merchantId": Record<string, never>
    "fields.name": Record<string, never>
    "fields.phones": Record<string, never>
    "fields.qrId": Record<string, never>
    "fields.qrLink": Record<string, never>
    "fields.region": Record<string, never>
    "fields.regionId": Record<string, never>
    "fields.status": Record<string, never>
    "fields.terminalId": Record<string, never>
    "fields.terminalType": Record<string, never>
    "fields.updatedAt": Record<string, never>
    "filters.allBanks": Record<string, never>
    "filters.allDistricts": Record<string, never>
    "filters.allMerchants": Record<string, never>
    "filters.allRegions": Record<string, never>
    "filters.banksFailed": Record<string, never>
    "filters.chooseRegion": Record<string, never>
    "filters.districtsFailed": Record<string, never>
    "filters.invalid": Record<string, never>
    "filters.merchantsFailed": Record<string, never>
    "filters.noBanks": Record<string, never>
    "filters.noDistricts": Record<string, never>
    "filters.noMerchantBanks": Record<string, never>
    "filters.noMerchants": Record<string, never>
    "filters.noRegions": Record<string, never>
    "filters.regionsFailed": Record<string, never>
    "filters.reselect": Record<string, never>
    "filters.unconfirmed": Record<string, never>
    "page.noAccess": Record<string, never>
    "page.terminals": Record<string, never>
    "page.unavailable": Record<string, never>
    "search.label": Record<string, never>
    "search.placeholder": Record<string, never>
    "states.empty": Record<string, never>
    "states.failed": Record<string, never>
    "states.loading": Record<string, never>
    "status.active": Record<string, never>
    "status.unknown": Record<string, never>
    "table.actions": Record<string, never>
    "table.label": Record<string, never>
    "table.pages": Record<string, never>
    "table.total": { "countText": string | number }
  }
  "bankAccounts": {
    "fields.account": Record<string, never>
    "fields.bank": Record<string, never>
    "fields.contract": Record<string, never>
    "fields.merchant": Record<string, never>
    "fields.mfo": Record<string, never>
    "fields.name": Record<string, never>
    "fields.status": Record<string, never>
    "fields.tin": Record<string, never>
    "filters.allMerchants": Record<string, never>
    "filters.invalid": Record<string, never>
    "filters.merchantsFailed": Record<string, never>
    "filters.noMerchants": Record<string, never>
    "filters.reselect": Record<string, never>
    "filters.unconfirmed": Record<string, never>
    "page.name": Record<string, never>
    "page.noAccess": Record<string, never>
    "page.unavailable": Record<string, never>
    "search.label": Record<string, never>
    "search.placeholder": Record<string, never>
    "states.empty": Record<string, never>
    "states.failed": Record<string, never>
    "states.loading": Record<string, never>
    "status.active": Record<string, never>
    "status.unknown": Record<string, never>
    "table.label": Record<string, never>
    "table.pages": Record<string, never>
    "table.total": { "countText": string | number }
  }
  "cashiers": {
    "actions.activeTerminals": { "countText": string | number }
    "actions.assign": Record<string, never>
    "actions.create": Record<string, never>
    "actions.new": Record<string, never>
    "actions.refreshStatus": Record<string, never>
    "actions.row": { "name": string | number }
    "actions.unassign": Record<string, never>
    "actions.unassignLabel": { "id": string | number; "name": string | number }
    "actions.unassignShort": Record<string, never>
    "assign.confirmed": Record<string, never>
    "assign.options": Record<string, never>
    "assign.pending": Record<string, never>
    "assign.selectionHelp": Record<string, never>
    "assign.submit": Record<string, never>
    "assign.title": Record<string, never>
    "assign.unknown": Record<string, never>
    "assign.warning": Record<string, never>
    "create.checkFirst": Record<string, never>
    "create.chooseTerminal": Record<string, never>
    "create.description": Record<string, never>
    "create.duplicateRisk": Record<string, never>
    "create.namePlaceholder": Record<string, never>
    "create.newIntent": Record<string, never>
    "create.pending": Record<string, never>
    "create.phoneHelp": Record<string, never>
    "create.phoneInvalid": Record<string, never>
    "create.submit": Record<string, never>
    "create.unknown": Record<string, never>
    "details.active": Record<string, never>
    "details.assigned": Record<string, never>
    "details.description": Record<string, never>
    "details.empty": Record<string, never>
    "details.terminalId": Record<string, never>
    "details.total": { "countText": string | number }
    "details.unassignHelp": Record<string, never>
    "details.unassignTarget": Record<string, never>
    "feedback.alreadySent": Record<string, never>
    "feedback.notSent": Record<string, never>
    "feedback.permission": Record<string, never>
    "feedback.rejected": Record<string, never>
    "feedback.selection": Record<string, never>
    "feedback.stale": Record<string, never>
    "feedback.unavailable": Record<string, never>
    "feedback.validation": Record<string, never>
    "fields.cashier": Record<string, never>
    "fields.fullname": Record<string, never>
    "fields.merchant": Record<string, never>
    "fields.phone": Record<string, never>
    "fields.role": Record<string, never>
    "fields.status": Record<string, never>
    "fields.terminal": Record<string, never>
    "fields.terminalId": Record<string, never>
    "filters.allMerchants": Record<string, never>
    "filters.allTerminals": Record<string, never>
    "filters.chooseMerchant": Record<string, never>
    "filters.invalid": Record<string, never>
    "filters.membership": Record<string, never>
    "filters.merchantsFailed": Record<string, never>
    "filters.noMerchants": Record<string, never>
    "filters.noMerchantTerminals": Record<string, never>
    "filters.reselect": Record<string, never>
    "filters.terminalsFailed": Record<string, never>
    "filters.unconfirmed": Record<string, never>
    "lookup.assignDenied": Record<string, never>
    "lookup.denied": Record<string, never>
    "lookup.failed": Record<string, never>
    "lookup.loading": Record<string, never>
    "lookup.unavailable": Record<string, never>
    "lookup.unconfirmed": Record<string, never>
    "page.name": Record<string, never>
    "page.noAccess": Record<string, never>
    "page.unavailable": Record<string, never>
    "search.label": Record<string, never>
    "search.placeholder": Record<string, never>
    "states.empty": Record<string, never>
    "states.failed": Record<string, never>
    "states.loading": Record<string, never>
    "status.active": Record<string, never>
    "status.inactive": Record<string, never>
    "status.unknown": Record<string, never>
    "table.actions": Record<string, never>
    "table.label": Record<string, never>
    "table.pages": Record<string, never>
    "table.total": { "countText": string | number }
    "unassign.confirm": Record<string, never>
    "unassign.confirmed": Record<string, never>
    "unassign.label": Record<string, never>
    "unassign.pending": Record<string, never>
    "unassign.stale": Record<string, never>
    "unassign.title": Record<string, never>
    "unassign.unknown": Record<string, never>
    "unassign.warning": { "cashier": string | number; "id": string | number; "terminal": string | number }
  }
  "p5": {
    "actions.details": Record<string, never>
    "actions.viewQr": Record<string, never>
    "details.device": Record<string, never>
    "details.qr": Record<string, never>
    "details.title": Record<string, never>
    "display.noLink": Record<string, never>
    "display.unavailable": Record<string, never>
    "fields.created": Record<string, never>
    "fields.createdAt": Record<string, never>
    "fields.description": Record<string, never>
    "fields.deviceId": Record<string, never>
    "fields.merchant": Record<string, never>
    "fields.qrId": Record<string, never>
    "fields.qrLink": Record<string, never>
    "fields.qrStatus": Record<string, never>
    "fields.status": Record<string, never>
    "fields.terminal": Record<string, never>
    "fields.terminalId": Record<string, never>
    "fields.terminalType": Record<string, never>
    "filters.all": Record<string, never>
    "filters.allMerchants": Record<string, never>
    "filters.allTerminals": Record<string, never>
    "filters.chooseMerchant": Record<string, never>
    "filters.codeInvalid": Record<string, never>
    "filters.codeValue": { "code": string | number }
    "filters.custom": Record<string, never>
    "filters.invalid": Record<string, never>
    "filters.merchantsFailed": Record<string, never>
    "filters.noMerchants": Record<string, never>
    "filters.noMerchantTerminals": Record<string, never>
    "filters.reselect": Record<string, never>
    "filters.status": Record<string, never>
    "filters.statusCode": Record<string, never>
    "filters.terminalsFailed": Record<string, never>
    "filters.unconfirmed": Record<string, never>
    "page.name": Record<string, never>
    "page.noAccess": Record<string, never>
    "page.unavailable": Record<string, never>
    "reset.action": Record<string, never>
    "reset.confirm": Record<string, never>
    "reset.confirmed": { "id": string | number }
    "reset.confirmedTitle": Record<string, never>
    "reset.newConfirm": Record<string, never>
    "reset.newRisk": Record<string, never>
    "reset.notSent": { "id": string | number }
    "reset.notSentTitle": Record<string, never>
    "reset.pending": Record<string, never>
    "reset.pendingCaption": Record<string, never>
    "reset.refreshFailed": Record<string, never>
    "reset.rejected": { "id": string | number }
    "reset.rejectedTitle": Record<string, never>
    "reset.terminal": { "name": string | number }
    "reset.title": Record<string, never>
    "reset.unavailable": Record<string, never>
    "reset.unknown": { "id": string | number }
    "reset.unknownTitle": Record<string, never>
    "reset.warning": { "id": string | number }
    "search.label": Record<string, never>
    "search.placeholder": Record<string, never>
    "states.contract": Record<string, never>
    "states.contractHelp": Record<string, never>
    "states.empty": Record<string, never>
    "states.failed": Record<string, never>
    "states.loading": Record<string, never>
    "status.active": Record<string, never>
    "status.inactive": Record<string, never>
    "status.qrActive": Record<string, never>
    "status.qrUnknown": Record<string, never>
    "status.unknown": Record<string, never>
    "table.actions": Record<string, never>
    "table.label": Record<string, never>
    "table.pages": Record<string, never>
    "table.total": { "countText": string | number }
  }
}
