// Generated by scripts/validate-locales.mjs --generate. Do not edit.
export const messageMetadata = {
  "common": {
    "actions.apply": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.cancel": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.clear": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.close": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.done": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.openMenu": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.refresh": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.reset": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.retry": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.save": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "copy.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "copy.link": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "copy.success": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.clearSelection": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "filters.close": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "greeting": {
      "plural": false,
      "params": [
        "name"
      ],
      "interpolations": [
        "name"
      ]
    },
    "items": {
      "plural": true,
      "params": [
        "count"
      ],
      "interpolations": [
        "count"
      ]
    },
    "locale.changeFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "locale.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "locale.selected": {
      "plural": false,
      "params": [
        "language"
      ],
      "interpolations": [
        "language"
      ]
    },
    "locale.switching": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pagination.next": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pagination.noPages": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pagination.page": {
      "plural": false,
      "params": [
        "page"
      ],
      "interpolations": [
        "page"
      ]
    },
    "pagination.pageSize": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pagination.pageSummary": {
      "plural": false,
      "params": [
        "count",
        "page"
      ],
      "interpolations": [
        "count",
        "page"
      ]
    },
    "pagination.perPage": {
      "plural": false,
      "params": [
        "size"
      ],
      "interpolations": [
        "size"
      ]
    },
    "pagination.previous": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pagination.total": {
      "plural": false,
      "params": [
        "value"
      ],
      "interpolations": [
        "value"
      ]
    },
    "phone.countryCode": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "refresh.updated": {
      "plural": false,
      "params": [
        "time"
      ],
      "interpolations": [
        "time"
      ]
    },
    "search.apply": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.clear": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.emptyDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.error": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.errorDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.loadingDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.loadingOption": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.noAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.noAccessDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.close": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.columns": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.hidden": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "table.move": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "table.moved": {
      "plural": false,
      "params": [
        "label",
        "position"
      ],
      "interpolations": [
        "label",
        "position"
      ]
    },
    "table.moveDown": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "table.moveUp": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "table.reset": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.restored": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.settings": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.shown": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "table.title": {
      "plural": false,
      "params": [
        "table"
      ],
      "interpolations": [
        "table"
      ]
    },
    "table.trigger": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.visibility": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "theme.current": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "theme.dark": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "theme.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "theme.light": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "theme.next": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "theme.system": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "toast.close": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "toast.notification": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "toast.viewport": {
      "plural": false,
      "params": [
        "hotkey"
      ],
      "interpolations": [
        "hotkey"
      ]
    }
  },
  "shell": {
    "header.demo": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "header.profile": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "header.profileMenu": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "header.user": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.account": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.bankAccounts": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.cashiers": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.close": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.collapse": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.dashboard": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.desktop": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.devices": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.dynamicQr": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.dynamicQrPreview": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.expand": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.home": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.main": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.mobile": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.open": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.sections": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.staticQr": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.staticQrPreview": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "navigation.terminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recovery.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recovery.reload": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recovery.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.accountLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.bankAccountsLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.cashiersLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.createQrLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.dashboardLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.devicesLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.dynamicQrLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.exportLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.forbidden": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.forbiddenDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.integrationUnavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.notFound": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.notFoundDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.returnSafe": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.sessionDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.sessionLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.staticQrLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.terminalsLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "routes.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.bankAccountsDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.bankAccountsTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.cashiersDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.cashiersTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.dashboardDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.dashboardTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.devicesDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.devicesTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.dynamicQrDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.dynamicQrTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.exportQrDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.exportQrTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.staticQrDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.staticQrTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.terminalsDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unavailable.terminalsTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "workspace": {
      "plural": false,
      "params": [],
      "interpolations": []
    }
  },
  "auth": {
    "actions.continue": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.forgotPin": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.logout": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.resend": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.restart": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.savePin": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.signIn": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.verify": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "brand.subtitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "completion.checking": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "completion.checkingDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "completion.complete": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "completion.completeDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "failure.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "failure.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.blocked": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.browserUnsupported": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.complete": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.completing": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.contract": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.deviceStorageUnavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.invalidOtp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.invalidPhone": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.invalidPin": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.otpExpired": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.otpNotExpired": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.ownerBusy": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.pinMismatch": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.rateLimited": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.request": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.sessionExpired": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.wrongOtp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.wrongPin": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "login.confirmDetails": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "login.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "login.phone": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "login.phoneSummary": {
      "plural": false,
      "params": [
        "phone"
      ],
      "interpolations": [
        "phone"
      ]
    },
    "login.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "logout.remoteUnconfirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "otp.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "otp.validity": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pin.confirm": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pin.createTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pin.hide": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pin.hideConfirmation": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pin.new": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pin.repeat": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pin.show": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pin.showConfirmation": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "pin.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.checking": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.saving": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.signingOut": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.waiting": {
      "plural": false,
      "params": [],
      "interpolations": []
    }
  },
  "account": {
    "actions.refresh": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.changed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.unchanged": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "profile.fullName": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "profile.missing": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "profile.phone": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.refreshing": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "title": {
      "plural": false,
      "params": [],
      "interpolations": []
    }
  },
  "dashboard": {
    "dates.choose": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "dates.graphPeriod": {
      "plural": false,
      "params": [
        "from",
        "to"
      ],
      "interpolations": [
        "from",
        "to"
      ]
    },
    "dates.hourAcross": {
      "plural": false,
      "params": [
        "end",
        "endDate",
        "start",
        "startDate"
      ],
      "interpolations": [
        "end",
        "endDate",
        "start",
        "startDate"
      ]
    },
    "dates.hourSame": {
      "plural": false,
      "params": [
        "date",
        "end",
        "start"
      ],
      "interpolations": [
        "date",
        "end",
        "start"
      ]
    },
    "dates.interval": {
      "plural": false,
      "params": [
        "end",
        "start"
      ],
      "interpolations": [
        "end",
        "start"
      ]
    },
    "dates.next": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "dates.previous": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "dates.reset": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "dates.week": {
      "plural": false,
      "params": [
        "date"
      ],
      "interpolations": [
        "date"
      ]
    },
    "donut.amountMismatch": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "donut.countMismatch": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "donut.details": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "donut.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "donut.relative": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "donut.shareItem": {
      "plural": false,
      "params": [
        "label",
        "percent"
      ],
      "interpolations": [
        "label",
        "percent"
      ]
    },
    "donut.successShare": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "donut.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "donut.total": {
      "plural": false,
      "params": [
        "countText"
      ],
      "interpolations": [
        "countText"
      ]
    },
    "donut.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allTerminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.dates": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.invalid": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noTerminal": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.preset": {
      "plural": true,
      "params": [
        "count"
      ],
      "interpolations": [
        "count"
      ]
    },
    "filters.presets": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.terminal": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.terminalError": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.terminalUnavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.AUTO": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.DAY": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.groupDAY": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.groupHOUR": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.groupMONTH": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.groupWEEK": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.groupYEAR": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.HOUR": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.MONTH": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.WEEK": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "granularity.YEAR": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "growth.downFavorable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "growth.downNeutral": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "growth.downUnfavorable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "growth.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "growth.unchanged": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "growth.upFavorable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "growth.upNeutral": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "growth.upUnfavorable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.failedDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.processing": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.processingDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.share": {
      "plural": false,
      "params": [
        "label"
      ],
      "interpolations": [
        "label"
      ]
    },
    "metrics.success": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.successDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.summary": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.total": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.totalDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "metrics.uncategorized": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "qrStatus.cancelled": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "qrStatus.expired": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "qrStatus.new": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "qrStatus.processing": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "qrStatus.rejected": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "qrStatus.success": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "qrStatus.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.actions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.amount": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.createdAt": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.error": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.qrId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.refreshing": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.stale": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.status": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.terminal": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.viewAll": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.viewDetails": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "recentQr.viewQr": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.integrationDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.integrationTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.noAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.stale": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.updatedAt": {
      "plural": false,
      "params": [
        "time"
      ],
      "interpolations": [
        "time"
      ]
    },
    "trend.amount": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.amountUnit": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.count": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.countUnit": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.coverageTitle": {
      "plural": false,
      "params": [
        "coverage",
        "title"
      ],
      "interpolations": [
        "coverage",
        "title"
      ]
    },
    "trend.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.exactDescription": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.exactItem": {
      "plural": false,
      "params": [
        "amount",
        "countText",
        "label"
      ],
      "interpolations": [
        "amount",
        "countText",
        "label"
      ]
    },
    "trend.exactTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.future": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.grouping": {
      "plural": false,
      "params": [
        "group"
      ],
      "interpolations": [
        "group"
      ]
    },
    "trend.keyboard": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.mode": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.partial": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.series": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.settings": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.settingsHelp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.settingsTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "trend.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    }
  },
  "dynamicQr": {
    "actions.details": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.new": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.viewQr": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.checkFirst": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.confirm": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.confirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.id": {
      "plural": false,
      "params": [
        "id"
      ],
      "interpolations": [
        "id"
      ]
    },
    "cancel.noRetry": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.notSent": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.notSentDetail": {
      "plural": false,
      "params": [
        "reason"
      ],
      "interpolations": [
        "reason"
      ]
    },
    "cancel.refreshFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.rejected": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "cancel.warning": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.amount": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.bounds": {
      "plural": false,
      "params": [
        "maximum",
        "minimum"
      ],
      "interpolations": [
        "maximum",
        "minimum"
      ]
    },
    "create.boundsUnavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.checkFirst": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.chooseTerminal": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.closed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.currenciesFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.currenciesLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.currenciesUnavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.currencyNoAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.dialogHelp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.example": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.linkUnavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.newRisk": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.noUzs": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.pending": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.resultHelp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.submit": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.terminalNoAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.terminalRemoved": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.terminalsEmpty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.terminalsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.terminalsLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.terminalsUnavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "dates.choose": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "dates.next": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "dates.previous": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "dates.reset": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.bankId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.baseAmount": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.currency": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.currencyAmount": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.distributionCode": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.linkSection": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.main": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.merchantId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.noLink": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.payment": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.rate": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.statusCode": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.technical": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.terminalId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.terminalName": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.terminalType": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.canonical": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.link": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.metadata": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.noLink": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.poster": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.posterAlt": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.qrTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "distribution.created": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "distribution.expired": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "distribution.rejected": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "download.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "download.pdf": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "download.png": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "download.posterFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "download.posterLoading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "export.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "export.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "export.pending": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "export.stop": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "export.success": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "export.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "export.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.alreadySent": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.copyId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.createNotSent": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.createRejected": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.idCopied": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.idFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.linkCopied": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.linkFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.permission": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.selection": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.all": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allBanks": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allTerminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.applySearch": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.banksFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.checking": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.checkOrClear": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.clear": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.clearSearch": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.clearSelection": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.distribution": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.invalid": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.merchantsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noBanks": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noExpansion": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchantBanks": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.search": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.searchShort": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.emptyHigh": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.first": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.firstHelp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.integration": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.list": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.name": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.noAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.pages": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.stale": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.total": {
      "plural": false,
      "params": [
        "countText"
      ],
      "interpolations": [
        "countText"
      ]
    },
    "stats.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "stats.fee": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "stats.total": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "stats.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.cancelled": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.expired": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.new": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.processing": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.rejected": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.success": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.actions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.amount": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.bank": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.createdAt": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.merchant": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.qrId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.rrn": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.state": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.status": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.terminal": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.updatedAt": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "validation.amount": {
      "plural": false,
      "params": [],
      "interpolations": []
    }
  },
  "staticQr": {
    "actions.details": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.viewQr": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.bounds": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.links": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.main": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.region": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.technical": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.noLink": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.createdAt": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.district": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.districtId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.link": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.maximum": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.merchant": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.merchantId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.minimum": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.qrId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.redirect": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.region": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.regionId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.status": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.statusCode": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminal": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminalId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminalName": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminalType": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.updatedAt": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allDistricts": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allRegions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allTerminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.chooseRegion": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.districtsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.invalid": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.merchantsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noDistricts": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchantTerminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noRegions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noTerminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.regionsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.reselect": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.terminalsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.unconfirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.authUnavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.name": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.noAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.placeholder": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.active": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.actions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.pages": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.total": {
      "plural": false,
      "params": [
        "countText"
      ],
      "interpolations": [
        "countText"
      ]
    }
  },
  "terminals": {
    "actions.details": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.viewQr": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.contact": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.location": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.main": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.qr": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.noLink": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.address": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.bank": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.bankId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.createdAt": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.district": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.districtId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.mcc": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.merchant": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.merchantId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.name": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.phones": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.qrId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.qrLink": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.region": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.regionId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.status": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminalId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminalType": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.updatedAt": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allBanks": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allDistricts": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allRegions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.banksFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.chooseRegion": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.districtsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.invalid": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.merchantsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noBanks": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noDistricts": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchantBanks": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noRegions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.regionsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.reselect": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.unconfirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.noAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.terminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.placeholder": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.active": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.actions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.pages": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.total": {
      "plural": false,
      "params": [
        "countText"
      ],
      "interpolations": [
        "countText"
      ]
    }
  },
  "bankAccounts": {
    "fields.account": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.bank": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.contract": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.merchant": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.mfo": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.name": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.status": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.tin": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.invalid": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.merchantsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.reselect": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.unconfirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.name": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.noAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.placeholder": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.active": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.pages": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.total": {
      "plural": false,
      "params": [
        "countText"
      ],
      "interpolations": [
        "countText"
      ]
    }
  },
  "cashiers": {
    "actions.activeTerminals": {
      "plural": false,
      "params": [
        "countText"
      ],
      "interpolations": [
        "countText"
      ]
    },
    "actions.assign": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.create": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.new": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.refreshStatus": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.row": {
      "plural": false,
      "params": [
        "name"
      ],
      "interpolations": [
        "name"
      ]
    },
    "actions.unassign": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.unassignLabel": {
      "plural": false,
      "params": [
        "id",
        "name"
      ],
      "interpolations": [
        "id",
        "name"
      ]
    },
    "actions.unassignShort": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "assign.confirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "assign.options": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "assign.pending": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "assign.selectionHelp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "assign.submit": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "assign.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "assign.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "assign.warning": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.checkFirst": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.chooseTerminal": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.duplicateRisk": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.namePlaceholder": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.newIntent": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.pending": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.phoneHelp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.phoneInvalid": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.submit": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "create.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.active": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.assigned": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.terminalId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.total": {
      "plural": false,
      "params": [
        "countText"
      ],
      "interpolations": [
        "countText"
      ]
    },
    "details.unassignHelp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.unassignTarget": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.alreadySent": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.notSent": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.permission": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.rejected": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.selection": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.stale": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "feedback.validation": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.cashier": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.fullname": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.merchant": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.phone": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.role": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.status": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminal": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminalId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allTerminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.chooseMerchant": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.invalid": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.membership": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.merchantsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchantTerminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.reselect": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.terminalsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.unconfirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "lookup.assignDenied": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "lookup.denied": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "lookup.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "lookup.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "lookup.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "lookup.unconfirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.name": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.noAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.placeholder": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.active": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.inactive": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.actions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.pages": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.total": {
      "plural": false,
      "params": [
        "countText"
      ],
      "interpolations": [
        "countText"
      ]
    },
    "unassign.confirm": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unassign.confirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unassign.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unassign.pending": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unassign.stale": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unassign.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unassign.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "unassign.warning": {
      "plural": false,
      "params": [
        "cashier",
        "id",
        "terminal"
      ],
      "interpolations": [
        "cashier",
        "id",
        "terminal"
      ]
    }
  },
  "p5": {
    "actions.details": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "actions.viewQr": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.device": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.qr": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "details.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.noLink": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "display.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.created": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.createdAt": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.description": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.deviceId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.merchant": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.qrId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.qrLink": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.qrStatus": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.status": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminal": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminalId": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "fields.terminalType": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.all": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.allTerminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.chooseMerchant": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.codeInvalid": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.codeValue": {
      "plural": false,
      "params": [
        "code"
      ],
      "interpolations": [
        "code"
      ]
    },
    "filters.custom": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.invalid": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.merchantsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchants": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.noMerchantTerminals": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.reselect": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.status": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.statusCode": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.terminalsFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "filters.unconfirmed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.name": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.noAccess": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "page.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.action": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.confirm": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.confirmed": {
      "plural": false,
      "params": [
        "id"
      ],
      "interpolations": [
        "id"
      ]
    },
    "reset.confirmedTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.newConfirm": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.newRisk": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.notSent": {
      "plural": false,
      "params": [
        "id"
      ],
      "interpolations": [
        "id"
      ]
    },
    "reset.notSentTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.pending": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.pendingCaption": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.refreshFailed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.rejected": {
      "plural": false,
      "params": [
        "id"
      ],
      "interpolations": [
        "id"
      ]
    },
    "reset.rejectedTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.terminal": {
      "plural": false,
      "params": [
        "name"
      ],
      "interpolations": [
        "name"
      ]
    },
    "reset.title": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.unavailable": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.unknown": {
      "plural": false,
      "params": [
        "id"
      ],
      "interpolations": [
        "id"
      ]
    },
    "reset.unknownTitle": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "reset.warning": {
      "plural": false,
      "params": [
        "id"
      ],
      "interpolations": [
        "id"
      ]
    },
    "search.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "search.placeholder": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.contract": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.contractHelp": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.empty": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.failed": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "states.loading": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.active": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.inactive": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.qrActive": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.qrUnknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "status.unknown": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.actions": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.label": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.pages": {
      "plural": false,
      "params": [],
      "interpolations": []
    },
    "table.total": {
      "plural": false,
      "params": [
        "countText"
      ],
      "interpolations": [
        "countText"
      ]
    }
  }
} as const
